// <auto-generated />
using System;
using FourtitudeIntegrated.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Prema.PriceHarborScraper.Migrations
{
    [DbContext(typeof(PriceHarborContext))]
    [Migration("20230925130637_addedParent")]
    partial class addedParent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.ParentGroup", b =>
                {
                    b.Property<int>("ProductGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParentGroupName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductGroupId");

                    b.ToTable("ParentGroup");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PlatformId");

                    b.ToTable("Platform");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.PriceChange", b =>
                {
                    b.Property<int>("PriceChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("PriceChangeId");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceChange");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("ProductGroupId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.ProductGroup", b =>
                {
                    b.Property<int>("ProductGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ParentGroupId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ProductGroupName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductGroupId");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("ProductGroup");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.PriceChange", b =>
                {
                    b.HasOne("Prema.PriceHarborScraper.Models.Product", "Product")
                        .WithMany("PriceChanges")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.Product", b =>
                {
                    b.HasOne("Prema.PriceHarborScraper.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.PriceHarborScraper.Models.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prema.PriceHarborScraper.Models.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Platform");

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.ProductGroup", b =>
                {
                    b.HasOne("Prema.PriceHarborScraper.Models.ParentGroup", "ParentGroup")
                        .WithMany("ProductGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.ParentGroup", b =>
                {
                    b.Navigation("ProductGroups");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.Product", b =>
                {
                    b.Navigation("PriceChanges");
                });

            modelBuilder.Entity("Prema.PriceHarborScraper.Models.ProductGroup", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
